import { createFileRoute } from '@tanstack/react-router'
import { uiLabels } from '@turystack/react-i18n'
import type { NotificationItem } from '@turystack/react-web'
import {
	Button,
	DropdownMenu,
	FormatProvider,
	LabelsProvider,
	NotificationCenter,
} from '@turystack/react-web'
import { Mail, MailOpen, MoreHorizontal, Trash2 } from 'lucide-react'
import type { ReactNode } from 'react'
import { useState } from 'react'

import {
	CodeBlock,
	ComponentPreview,
	PropsTable,
	SlotsSection,
} from '@/components/docs'
import {
	notificationSamples,
	useDemoInbox,
} from '@/data/react-web-notifications'

/**
 * Props read from
 * `react-web/src/components/notification-center/notification-center.types.ts`
 * and the destructuring defaults in `notification-center.tsx`. The data union
 * is List's: `items` (+ `loading`) or `outcome`, never both.
 */
const notificationCenterProps = [
	{
		description: 'The notifications, newest first.',
		name: 'items',
		type: 'NotificationItem[]',
	},
	{
		default: 'false',
		description: 'Initial load: skeleton rows in the popover.',
		name: 'loading',
		type: 'boolean',
	},
	{
		description: 'The five states of a remote read, instead of items.',
		name: 'outcome',
		type: 'DataOutcome<NotificationItem[]>',
	},
	{
		default: 'the unread items',
		description: 'What the bell counts, usually from the server.',
		name: 'unreadCount',
		type: 'number',
	},
	{
		default: '5',
		description: 'Rows in the popover.',
		name: 'limit',
		type: 'number',
	},
	{
		description: 'Activates a row and closes the popover; never marks read.',
		name: 'onItemClick',
		type: '(item: NotificationItem) => void',
	},
	{
		description: 'A row’s own controls — in the sheet only.',
		name: 'itemActions',
		type: '(item: NotificationItem) => React.ReactNode',
	},
	{
		description: 'Shows “Mark all as read” while something is unread.',
		name: 'onMarkAllRead',
		type: '() => void',
	},
	{
		description: 'A link to a notifications page, or the built-in sheet.',
		name: 'viewAll',
		type: '{ href: string } | "sheet"',
	},
	{
		description: 'The sheet’s list: a further page exists.',
		name: 'hasMore',
		type: 'boolean',
	},
	{
		default: 'false',
		description: 'The sheet’s list: a further page is loading.',
		name: 'loadingMore',
		type: 'boolean',
	},
	{
		description: 'The sheet’s list: loads the next page.',
		name: 'onLoadMore',
		type: '() => void',
	},
	{
		description: 'The sheet’s list: shown once nothing is left to load.',
		name: 'endReachedSection',
		type: 'React.ReactNode',
	},
	{
		description: 'Controlled popover visibility.',
		name: 'open',
		type: 'boolean',
	},
	{
		default: 'false',
		description: 'Uncontrolled initial visibility.',
		name: 'defaultOpen',
		type: 'boolean',
	},
	{
		description: 'Fires when the popover opens or closes.',
		name: 'onOpenChange',
		type: '(open: boolean) => void',
	},
	{
		description: 'Controlled sheet visibility (viewAll="sheet").',
		name: 'sheetOpen',
		type: 'boolean',
	},
	{
		default: 'false',
		description: 'Uncontrolled initial sheet visibility.',
		name: 'defaultSheetOpen',
		type: 'boolean',
	},
	{
		description: 'Fires when the sheet opens or closes.',
		name: 'onSheetOpenChange',
		type: '(open: boolean) => void',
	},
	{
		description: 'Replaces the “You’re all caught up” state.',
		name: 'emptySection',
		type: 'React.ReactNode',
	},
	{
		default: '"ghost"',
		description: 'The bell’s button style.',
		name: 'triggerVariant',
		type: '"ghost" | "outline"',
	},
	{
		default: '"sm"',
		description: 'The bell’s button size.',
		name: 'triggerSize',
		type: '"sm" | "md"',
	},
	{
		default: 'labels.notifications.trigger(unread)',
		description: 'Replaces the bell’s whole accessible name, count included.',
		name: 'ariaLabel',
		type: 'string',
	},
]

const usageCode = `import { NotificationCenter } from '@turystack/react-web'

<NotificationCenter
  items={notifications}
  onItemClick={(n) => navigate(n.href)}
  onMarkAllRead={markAllRead}
  viewAll="sheet"
/>

<NotificationCenter
  outcome={outcome}
  unreadCount={meta.unread}
  viewAll={{ href: '/notifications' }}
/>`

const wiringCode = `// The app layer. NotificationCenter never imports the SDK, the router or kubb:
// a kubb hook → useInfiniteDataOutcome → the pure component.
import { useInfiniteDataOutcome } from '@turystack/react-hooks'
import { NotificationCenter, type NotificationItem } from '@turystack/react-web'
import {
  useListNotificationsInfinite,
  useMarkAllNotificationsRead,
  useMarkNotificationRead,
} from '@/gen/hooks' // generated by kubb

const toItem = (n: Notification): NotificationItem => ({
  at: new Date(n.created_at),
  description: n.body,
  href: n.link ?? undefined,
  id: n.notification_id,
  read: n.read_at !== null,
  title: n.title,
})

export function TopBarNotifications() {
  const query = useListNotificationsInfinite({ limit: 20 })
  const markRead = useMarkNotificationRead()
  const markAllRead = useMarkAllNotificationsRead()

  const { outcome, hasMore, loadingMore, onLoadMore } = useInfiniteDataOutcome({
    query,
    select: (pages) => pages.flatMap((page) => page.data.map(toItem)),
  })

  return (
    <NotificationCenter
      hasMore={hasMore}
      loadingMore={loadingMore}
      onItemClick={(n) => markRead.mutate({ notification_id: n.id })}
      onLoadMore={onLoadMore}
      onMarkAllRead={() => markAllRead.mutate()}
      outcome={outcome}
      unreadCount={query.data?.pages[0]?.meta.unread}
      viewAll="sheet"
    />
  )
}

// One page, not infinite? useDataOutcome does the same for a plain query:
// const outcome = useDataOutcome({ query: useListNotifications(), select: (p) => p.data.map(toItem) })`

function RowMenu({
	item,
	onDelete,
	onToggleRead,
}: {
	item: NotificationItem
	onDelete: (item: NotificationItem) => void
	onToggleRead: (item: NotificationItem) => void
}) {
	return (
		<DropdownMenu>
			<DropdownMenu.Trigger asChild>
				<Button
					ariaLabel="Ações da notificação"
					size="icon-sm"
					variant="ghost"
				>
					<MoreHorizontal />
				</Button>
			</DropdownMenu.Trigger>
			<DropdownMenu.Content
				align="end"
				width={220}
			>
				<DropdownMenu.Item onClick={() => onToggleRead(item)}>
					{item.read ? <Mail /> : <MailOpen />}
					{item.read ? 'Marcar como não lida' : 'Marcar como lida'}
				</DropdownMenu.Item>
				<DropdownMenu.Separator />
				<DropdownMenu.Item
					onClick={() => onDelete(item)}
					variant="destructive"
				>
					<Trash2 /> Excluir
				</DropdownMenu.Item>
			</DropdownMenu.Content>
		</DropdownMenu>
	)
}

/** A strip that reads as an app's top bar, so the bell sits where it lives. */
function TopBar({ children }: { children: ReactNode }) {
	return (
		<div className="flex w-full items-center justify-between gap-4 rounded-lg border border-border bg-card px-4 py-2">
			<span className="font-semibold text-sm">Acme</span>
			<div className="flex items-center gap-2">{children}</div>
		</div>
	)
}

function Page() {
	const inbox = useDemoInbox()
	const ptInbox = useDemoInbox()
	const sheetInbox = useDemoInbox()
	const [lastEvent, setLastEvent] = useState('nenhum')
	const [open, setOpen] = useState(false)
	const [sheetOpen, setSheetOpen] = useState(false)

	return (
		<div className="space-y-10">
			<header>
				<p className="font-medium text-lib text-xs uppercase tracking-wider">
					Notifications
				</p>
				<h1 className="mt-2 font-bold font-display text-3xl tracking-tight">
					NotificationCenter
				</h1>
				<p className="mt-3 max-w-prose text-lg text-muted-foreground">
					The bell in the top bar: how many are waiting, the latest few in a
					popover, and a way to all of them.
				</p>
			</header>

			<section className="space-y-4">
				<h2 className="font-display font-semibold text-xl">Props</h2>
				<PropsTable props={notificationCenterProps} />
			</section>

			<SlotsSection slug="notification-center" />

			<section className="space-y-4">
				<h2 className="font-display font-semibold text-xl">
					Popover and sheet
				</h2>
				<p className="max-w-prose text-muted-foreground text-sm">
					The popover shows the latest five.{' '}
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						viewAll="sheet"
					</code>{' '}
					adds a side sheet with all of them by day, an All / Unread filter and{' '}
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						itemActions
					</code>
					.
				</p>
				<ComponentPreview
					className="items-stretch"
					title='viewAll="sheet" + itemActions + infinite'
				>
					<div className="w-full space-y-3">
						<TopBar>
							<NotificationCenter
								endReachedSection="Isso é tudo dos últimos 90 dias."
								hasMore={inbox.hasMore}
								itemActions={(item) => (
									<RowMenu
										item={item}
										onDelete={(target) => {
											inbox.remove(target.id)
											setLastEvent(`excluiu ${target.id}`)
										}}
										onToggleRead={(target) => {
											inbox.setRead(target.id, !target.read)
											setLastEvent(
												`${target.read ? 'marcou como não lida' : 'marcou como lida'} ${target.id}`,
											)
										}}
									/>
								)}
								items={inbox.items}
								loadingMore={inbox.loadingMore}
								onItemClick={(item) => {
									inbox.setRead(item.id, true)
									setLastEvent(`abriu ${item.id}`)
								}}
								onLoadMore={inbox.loadMore}
								onMarkAllRead={() => {
									inbox.markAllRead()
									setLastEvent('marcou todas como lidas')
								}}
								viewAll="sheet"
							/>
						</TopBar>
						<div className="flex items-center justify-between gap-3">
							<p className="text-muted-foreground text-xs">
								último evento: <code>{lastEvent}</code>
							</p>
							<Button
								onClick={() => {
									inbox.reset()
									setLastEvent('nenhum')
								}}
								size="sm"
								variant="outline"
							>
								Reset
							</Button>
						</div>
					</div>
				</ComponentPreview>
			</section>

			<section className="space-y-4">
				<h2 className="font-display font-semibold text-xl">
					View all as a link
				</h2>
				<p className="max-w-prose text-muted-foreground text-sm">
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						{'viewAll={{ href }}'}
					</code>{' '}
					makes “View all” a link.{' '}
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						unreadCount
					</code>{' '}
					comes from the server; above 99 the bell reads “99+”.
				</p>
				<ComponentPreview title="viewAll={{ href }} + unreadCount={128}">
					<TopBar>
						<NotificationCenter
							items={notificationSamples}
							unreadCount={128}
							viewAll={{
								href: '/libs/react-web/components/notification-list',
							}}
						/>
					</TopBar>
				</ComponentPreview>
			</section>

			<section className="space-y-4">
				<h2 className="font-display font-semibold text-xl">
					Empty and loading
				</h2>
				<p className="max-w-prose text-muted-foreground text-sm">
					With nothing unread the bell has no count and “Mark all as read” is
					hidden, even with{' '}
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						onMarkAllRead
					</code>
					.
				</p>
				<ComponentPreview title="items={[]}, loading, outcome pending">
					<div className="flex items-center gap-8">
						<div className="flex flex-col items-center gap-2">
							<NotificationCenter
								items={[]}
								onMarkAllRead={() => undefined}
								triggerVariant="outline"
							/>
							<span className="font-mono text-muted-foreground text-xs">
								empty
							</span>
						</div>
						<div className="flex flex-col items-center gap-2">
							<NotificationCenter
								items={[]}
								loading
								triggerVariant="outline"
							/>
							<span className="font-mono text-muted-foreground text-xs">
								loading
							</span>
						</div>
						<div className="flex flex-col items-center gap-2">
							<NotificationCenter
								outcome={{
									retry: () => undefined,
									status: 'pending',
								}}
								triggerVariant="outline"
							/>
							<span className="font-mono text-muted-foreground text-xs">
								outcome pending
							</span>
						</div>
					</div>
				</ComponentPreview>
			</section>

			<section className="space-y-4">
				<h2 className="font-display font-semibold text-xl">
					Trigger and controlled open
				</h2>
				<p className="max-w-prose text-muted-foreground text-sm">
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						triggerVariant
					</code>{' '}
					and{' '}
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						triggerSize
					</code>{' '}
					style the bell;{' '}
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						open
					</code>{' '}
					/{' '}
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						onOpenChange
					</code>{' '}
					control the popover.
				</p>
				<ComponentPreview title="triggerVariant, triggerSize, controlled open">
					<div className="flex items-center gap-4">
						<NotificationCenter
							items={notificationSamples}
							limit={3}
							onOpenChange={setOpen}
							open={open}
							triggerSize="md"
							triggerVariant="outline"
						/>
						<Button
							onClick={() => setOpen(true)}
							size="sm"
							variant="ghost"
						>
							Abrir de fora
						</Button>
						<span className="font-mono text-muted-foreground text-xs">
							open={String(open)}
						</span>
					</div>
				</ComponentPreview>
			</section>

			<section className="space-y-4">
				<h2 className="font-display font-semibold text-xl">Controlled sheet</h2>
				<p className="max-w-prose text-muted-foreground text-sm">
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						sheetOpen
					</code>{' '}
					/{' '}
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						onSheetOpenChange
					</code>{' '}
					control the sheet, so a page can open it without the bell;{' '}
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						defaultSheetOpen
					</code>{' '}
					starts it open.
				</p>
				<ComponentPreview title='viewAll="sheet" + sheetOpen + onSheetOpenChange'>
					<div className="flex items-center gap-4">
						<NotificationCenter
							items={sheetInbox.items}
							onItemClick={(item) => sheetInbox.setRead(item.id, true)}
							onSheetOpenChange={setSheetOpen}
							sheetOpen={sheetOpen}
							viewAll="sheet"
						/>
						<Button
							onClick={() => setSheetOpen(true)}
							size="sm"
							variant="outline"
						>
							Abrir a caixa de entrada
						</Button>
						<span className="font-mono text-muted-foreground text-xs">
							sheetOpen={String(sheetOpen)}
						</span>
					</div>
				</ComponentPreview>
			</section>

			<section className="space-y-4">
				<h2 className="font-display font-semibold text-xl">In Portuguese</h2>
				<p className="max-w-prose text-muted-foreground text-sm">
					react-i18n’s pt-BR labels and a pt-BR FormatProvider translate every
					string and time: “Notificações, 4 não lidas”, “Hoje”.
				</p>
				<ComponentPreview title="LabelsProvider pt-br + FormatProvider pt-BR">
					<LabelsProvider labels={uiLabels['pt-br']}>
						<FormatProvider
							format={{
								locale: 'pt-BR',
								timeZone: 'America/Sao_Paulo',
							}}
						>
							<TopBar>
								<NotificationCenter
									items={ptInbox.items}
									onItemClick={(item) => ptInbox.setRead(item.id, true)}
									onMarkAllRead={ptInbox.markAllRead}
									viewAll="sheet"
								/>
							</TopBar>
						</FormatProvider>
					</LabelsProvider>
				</ComponentPreview>
			</section>

			<section className="space-y-4">
				<h2 className="font-display font-semibold text-xl">Usage</h2>
				<CodeBlock
					code={usageCode}
					filename="example.tsx"
					language="tsx"
				/>
			</section>

			<section className="space-y-4">
				<h2 className="font-display font-semibold text-xl">
					Wiring to the SDK
				</h2>
				<p className="max-w-prose text-muted-foreground text-sm">
					The app adapts the kubb query with{' '}
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						useInfiniteDataOutcome
					</code>{' '}
					(or{' '}
					<code className="rounded-lg bg-muted px-1.5 py-0.5 text-xs">
						useDataOutcome
					</code>
					) and maps rows to NotificationItem.
				</p>
				<CodeBlock
					code={wiringCode}
					filename="top-bar-notifications.tsx"
					language="tsx"
				/>
			</section>
		</div>
	)
}

export const Route = createFileRoute(
	'/libs/react-web/components/notification-center',
)({
	component: Page,
})
