/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as LibsUiRouteImport } from './routes/libs/ui'
import { Route as LibsUiIndexRouteImport } from './routes/libs/ui/index'
import { Route as LibsUiButtonRouteImport } from './routes/libs/ui/button'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const LibsUiRoute = LibsUiRouteImport.update({
  id: '/libs/ui',
  path: '/libs/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const LibsUiIndexRoute = LibsUiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibsUiRoute,
} as any)
const LibsUiButtonRoute = LibsUiButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => LibsUiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/libs/ui': typeof LibsUiRouteWithChildren
  '/libs/ui/button': typeof LibsUiButtonRoute
  '/libs/ui/': typeof LibsUiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/libs/ui/button': typeof LibsUiButtonRoute
  '/libs/ui': typeof LibsUiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/libs/ui': typeof LibsUiRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/libs/ui/button': typeof LibsUiButtonRoute
  '/libs/ui/': typeof LibsUiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/libs/ui' | '/libs/ui/button' | '/libs/ui/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/libs/ui/button' | '/libs/ui'
  id:
    | '__root__'
    | '/_main'
    | '/libs/ui'
    | '/_main/'
    | '/libs/ui/button'
    | '/libs/ui/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  LibsUiRoute: typeof LibsUiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/libs/ui': {
      id: '/libs/ui'
      path: '/libs/ui'
      fullPath: '/libs/ui'
      preLoaderRoute: typeof LibsUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libs/ui/': {
      id: '/libs/ui/'
      path: '/'
      fullPath: '/libs/ui/'
      preLoaderRoute: typeof LibsUiIndexRouteImport
      parentRoute: typeof LibsUiRoute
    }
    '/libs/ui/button': {
      id: '/libs/ui/button'
      path: '/button'
      fullPath: '/libs/ui/button'
      preLoaderRoute: typeof LibsUiButtonRouteImport
      parentRoute: typeof LibsUiRoute
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface LibsUiRouteChildren {
  LibsUiButtonRoute: typeof LibsUiButtonRoute
  LibsUiIndexRoute: typeof LibsUiIndexRoute
}

const LibsUiRouteChildren: LibsUiRouteChildren = {
  LibsUiButtonRoute: LibsUiButtonRoute,
  LibsUiIndexRoute: LibsUiIndexRoute,
}

const LibsUiRouteWithChildren =
  LibsUiRoute._addFileChildren(LibsUiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  LibsUiRoute: LibsUiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
