/**
 * Generated by scripts/proof-mode-report-shape.mjs — do not edit.
 *
 * Derived from @turystack/proof-mode-gates' own templates/report.html and its
 * CLI help, so this page cannot describe a report the runner does not emit.
 * Run `pnpm report-shape:write` after changing either.
 */

export type ReportBlock = {
	name: string
	shape: string
	stops: string
}

export type ReportCommand = {
	command: string
	does: string
}

export const reportBlocks: ReportBlock[] = [
	{
		"name": "schema",
		"shape": "string",
		"stops": "a renderer computing a verdict from a payload it cannot read"
	},
	{
		"name": "task",
		"shape": "{ id, title, board, covers, branch, baseline, commit, author, finishedAt, durationMs }",
		"stops": "a report describing a different commit than the one under review"
	},
	{
		"name": "provenance",
		"shape": "{ runner, skills }",
		"stops": "green under one version of a skill read as evidence under another"
	},
	{
		"name": "ladder",
		"shape": "[{ id, name, command, state, result, note }]",
		"stops": "\"it works on my machine\""
	},
	{
		"name": "changed",
		"shape": "{ files, added, removed, untested, entries }",
		"stops": "green whose scope nobody checked"
	},
	{
		"name": "context",
		"shape": "[{ kind, title, source, resolvedBy }]",
		"stops": "work built over a missing input (DLV-1)"
	},
	{
		"name": "law",
		"shape": "{ total, touched, automated, manual, violations, bindings }",
		"stops": "a `manual` binding read as automatically satisfied"
	},
	{
		"name": "backend",
		"shape": "{ coverage, specs, endpoints, migrations, docsShot }",
		"stops": "a spec nobody tested, and a migration nobody described"
	},
	{
		"name": "contractDelta",
		"shape": "[{ kind, change, name, breaking, note }]",
		"stops": "a breaking change discovered by a consumer (DLV-15)"
	},
	{
		"name": "frontend",
		"shape": "{ coverage, specs, outcomes, accessibility, bundle, screens }",
		"stops": "a happy-path screenshot standing in for five states"
	},
	{
		"name": "raw",
		"shape": "{ biome, vitest, coverage }",
		"stops": "a green summary the tools never actually printed"
	}
]

export const reportCommands: ReportCommand[] = [
	{
		"command": "turystack-proof run [--out <dir>]",
		"does": "the whole ladder, in order, then the report"
	},
	{
		"command": "turystack-proof run --dry-run",
		"does": "the rungs it would run, and on what - runs nothing"
	},
	{
		"command": "turystack-proof next [--json]",
		"does": "what is open, and why - no LLM"
	},
	{
		"command": "turystack-proof next --markdown",
		"does": "the same, as a digest to paste or pipe"
	},
	{
		"command": "turystack-proof structure [--json]",
		"does": "only the structural checks"
	},
	{
		"command": "turystack-proof report [--out <dir>]",
		"does": "emit gate-report.json and .html"
	},
	{
		"command": "turystack-proof skill [<dir>]",
		"does": "validate one skill package on its own"
	},
	{
		"command": "turystack-proof howto [<dir>]",
		"does": "a materialized skill's start-here comments"
	},
	{
		"command": "turystack-proof howto [<dir>] --strip",
		"does": "removes them, once the skill is started"
	},
	{
		"command": "turystack-proof board --write <dir>",
		"does": "render a blueprint's docs.json and board"
	},
	{
		"command": "turystack-proof board --check <dir>",
		"does": "the files --write would change; exits 1"
	}
]
